# Generated by Django 5.1 on 2024-08-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Speakers',
            field=models.CharField(default='Ahmed Skr', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='MOhamed salah', max_length=200),
        ),
    ]
