# Generated by Django 5.1 on 2024-08-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='MOhamed salah@hotmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='registration',
            name='name',
            field=models.CharField(default='MOhamed salah', max_length=100),
        ),
    ]
